export default {
  namespaced: true,
  state: {
    items: [
      {
        id: 0,
        month: 'Август',
        date: '12',
        episode: '1 серия',
        episode2: '2 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-1.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-1-mobile.png'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 1,
        date: '19',
        episode: '3 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-3.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-3-mobile.png'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 2,
        date: '26',
        episode: '4 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-4.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-4-mobile.png'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 3,
        month: 'Сентябрь',
        date: '2',
        episode: '5 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-5.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-5-mobile.jpg'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 4,
        date: '9',
        episode: '6 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-6.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-6-mobile.jpg'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 5,
        date: '16',
        episode: '7 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-7.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-7-mobile.jpg'),
        available: true,
        hoverCheck: false,
      },
      {
        id: 6,
        date: '23',
        episode: '8 серия',
        href: 'https://okko.tv/serial/vyzhivshie?utm_source=afisha&utm_medium=spec&utm_campaign=afisha_survivors&utm_content=button_calendar_watch',
        imgBg: require('@/assets/img/calendar/calendar-bg-8.jpg'),
        imgBgMobile: require('@/assets/img/calendar/calendar-bg-8-mobile.jpg'),
        available: true,
        hoverCheck: false,
      },
    ]
  },
  getters: {
    getCalendarById: state => id => state.items.find(item => item.id === id),
  }
}